### ISSUE TITLE
Show the heatmap visually or save the json

### ISSUE THREAD

**Issue by buggyzap** [JointlyTech/spyone#5]
What do you think about an optional argument that let the user to show the heatmap visually ( via a specific frontend that show the generated json visually with the help of library like d3.js ).

And the --save argument, that save the .json directly in a specific folder, that let the users to use it in other contexts like CI.

**Comment by Cadienvan** [comment]
Hi @buggyzap we brought in #6 which does one part of what you suggested here, the '--save' argument is a nice addition, do you wanna go with that?

**Comment by buggyzap** [comment]
> Hi @buggyzap we brought in #6 which does one part of what you suggested here, the '--save' argument is a nice addition, do you wanna go with that?

Ok I'll try asap

**Comment by buggyzap** [comment]
I'm waiting for #7 first, as I suggest, we need to keep args and also have the interactive version.

After that I'll provide new --save argument.

**Comment by Cadienvan** [comment]
Moved the development related to this issue to #8 so that the issue will automatically close when we merge it.
